apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foxbit-calc.fullname" . }}
  labels:
    {{- include "foxbit-calc.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  LOG_FORMAT: {{ .Values.logging.format | quote }}
  CALC_DELAY: {{ .Values.calcDelay | quote }}
  CACHE_ENABLED: {{ .Values.cache.enabled | quote }}
  {{- if .Values.cache.enabled }}
  CACHE_TTL: {{ .Values.cache.ttl | quote }}
  REDIS_ADDR: {{ include "foxbit-calc.redisAddress" . | quote }}
  {{- if eq .Values.cache.type "external" }}
  REDIS_DB: {{ .Values.cache.external.db | quote }}
  {{- end }}
  {{- end }}
