// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// CalculationResult defines model for CalculationResult.
type CalculationResult struct {
	// Result Resultado da operação. Inteiro quando `precision` é omitido,
	// decimal (truncado a `precision` casas) caso contrário.
	Result float64 `json:"result"`
}

// Error defines model for Error.
type Error struct {
	// Message Descrição legível do erro.
	Message string `json:"message"`
}

// Precision defines model for Precision.
type Precision = int

// TermOne defines model for TermOne.
type TermOne = float64

// TermTwo defines model for TermTwo.
type TermTwo = float64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// DivideParams defines parameters for Divide.
type DivideParams struct {
	// TermOne Primeiro termo da operação.
	TermOne TermOne `form:"term_one" json:"term_one"`

	// TermTwo Segundo termo da operação.
	TermTwo TermTwo `form:"term_two" json:"term_two"`

	// Precision Número de casas decimais do resultado (truncado, sem arredondar).
	// Quando ausente, o resultado é truncado para inteiro.
	Precision *Precision `form:"precision,omitempty" json:"precision,omitempty"`
}

// MultiplyParams defines parameters for Multiply.
type MultiplyParams struct {
	// TermOne Primeiro termo da operação.
	TermOne TermOne `form:"term_one" json:"term_one"`

	// TermTwo Segundo termo da operação.
	TermTwo TermTwo `form:"term_two" json:"term_two"`

	// Precision Número de casas decimais do resultado (truncado, sem arredondar).
	// Quando ausente, o resultado é truncado para inteiro.
	Precision *Precision `form:"precision,omitempty" json:"precision,omitempty"`
}

// SubtractParams defines parameters for Subtract.
type SubtractParams struct {
	// TermOne Primeiro termo da operação.
	TermOne TermOne `form:"term_one" json:"term_one"`

	// TermTwo Segundo termo da operação.
	TermTwo TermTwo `form:"term_two" json:"term_two"`

	// Precision Número de casas decimais do resultado (truncado, sem arredondar).
	// Quando ausente, o resultado é truncado para inteiro.
	Precision *Precision `form:"precision,omitempty" json:"precision,omitempty"`
}

// SumParams defines parameters for Sum.
type SumParams struct {
	// TermOne Primeiro termo da operação.
	TermOne TermOne `form:"term_one" json:"term_one"`

	// TermTwo Segundo termo da operação.
	TermTwo TermTwo `form:"term_two" json:"term_two"`

	// Precision Número de casas decimais do resultado (truncado, sem arredondar).
	// Quando ausente, o resultado é truncado para inteiro.
	Precision *Precision `form:"precision,omitempty" json:"precision,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Divisão (term_one / term_two)
	// (GET /api/div)
	Divide(ctx echo.Context, params DivideParams) error
	// Multiplicação (term_one * term_two)
	// (GET /api/mul)
	Multiply(ctx echo.Context, params MultiplyParams) error
	// Subtração (term_one - term_two)
	// (GET /api/sub)
	Subtract(ctx echo.Context, params SubtractParams) error
	// Adição (term_one + term_two)
	// (GET /api/sum)
	Sum(ctx echo.Context, params SumParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Divide converts echo context to params.
func (w *ServerInterfaceWrapper) Divide(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DivideParams
	// ------------- Required query parameter "term_one" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_one", ctx.QueryParams(), &params.TermOne)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_one: %s", err))
	}

	// ------------- Required query parameter "term_two" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_two", ctx.QueryParams(), &params.TermTwo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_two: %s", err))
	}

	// ------------- Optional query parameter "precision" -------------

	err = runtime.BindQueryParameter("form", true, false, "precision", ctx.QueryParams(), &params.Precision)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter precision: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Divide(ctx, params)
	return err
}

// Multiply converts echo context to params.
func (w *ServerInterfaceWrapper) Multiply(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params MultiplyParams
	// ------------- Required query parameter "term_one" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_one", ctx.QueryParams(), &params.TermOne)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_one: %s", err))
	}

	// ------------- Required query parameter "term_two" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_two", ctx.QueryParams(), &params.TermTwo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_two: %s", err))
	}

	// ------------- Optional query parameter "precision" -------------

	err = runtime.BindQueryParameter("form", true, false, "precision", ctx.QueryParams(), &params.Precision)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter precision: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Multiply(ctx, params)
	return err
}

// Subtract converts echo context to params.
func (w *ServerInterfaceWrapper) Subtract(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SubtractParams
	// ------------- Required query parameter "term_one" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_one", ctx.QueryParams(), &params.TermOne)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_one: %s", err))
	}

	// ------------- Required query parameter "term_two" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_two", ctx.QueryParams(), &params.TermTwo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_two: %s", err))
	}

	// ------------- Optional query parameter "precision" -------------

	err = runtime.BindQueryParameter("form", true, false, "precision", ctx.QueryParams(), &params.Precision)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter precision: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Subtract(ctx, params)
	return err
}

// Sum converts echo context to params.
func (w *ServerInterfaceWrapper) Sum(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SumParams
	// ------------- Required query parameter "term_one" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_one", ctx.QueryParams(), &params.TermOne)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_one: %s", err))
	}

	// ------------- Required query parameter "term_two" -------------

	err = runtime.BindQueryParameter("form", true, true, "term_two", ctx.QueryParams(), &params.TermTwo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter term_two: %s", err))
	}

	// ------------- Optional query parameter "precision" -------------

	err = runtime.BindQueryParameter("form", true, false, "precision", ctx.QueryParams(), &params.Precision)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter precision: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Sum(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/div", wrapper.Divide)
	router.GET(baseURL+"/api/mul", wrapper.Multiply)
	router.GET(baseURL+"/api/sub", wrapper.Subtract)
	router.GET(baseURL+"/api/sum", wrapper.Sum)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW8jRRP9K6X+voMNg+1sFglZ4hDCIuWwEJLc1hEuT1e8vZrumlR3exNW/jFhD4gD",
	"Ry5c/cdQz3hmnNhevBIHJPYUd1xd9frVe1V+p3K2JTtywavxO1WioKVAUp3OhXLjDbt00ORzMWWojur7",
	"1Z+WhEET5OjRg6bcWDQeNIOQj0VAzdALEl2OmjPwZAFFSLPTKP3BxP0Y0WkGjJ5coAw2L65+g+YqJFBg",
	"XCAjPJg4lSmTINxGknuVKYeW1FiVLdhM+fw1WUyo6Q5tWZAaP8uUxTtjo1Xjoy8zZY2rD6NMhfsyZUgl",
	"5iRquczUFYn9wdH2w8/F2AQEAoll0AhckuDq19V7HuyBlkJ/YkcqU0K30QhpNQ4SaSfS55m6YbEY1Fhp",
	"jrMi3VtDdNHONhBeveVthJc0j4nXjwUY3vJhAI8OAbhMqXzJzlOlpW9QX9BtJB/SKWcXyFUfsSwLk2MC",
	"P3zja611Rf8vdKPG6n/DTqfD+ls/fCHC61KPGUiFjDfVk8G4xeqhMBqhV6KsfrEUhH2jOg8c2xD2/YFa",
	"ZuoUizwWFaSLSpH/GOTtzDvhNy540rwUus6UCu2EWUq6EUzNurT/P6wEnNU2g9vam9PWVdNkSbYmGM3Z",
	"xNV2LzqDAz4KroZCP/1hSMzJ6kHM2r2tkI4PU3onyVfNg67bOJ69oTykrtVy2KLAkvc43+Hkb6tTLZKC",
	"5qvfF1Sk6UUilVFamK09wEYfwHGAGcHPJNzB9UGMm2/BbYpv402Rxt3s8O/J+RlcvLi8gttIQHeUx4CA",
	"PrUkCLfd+oM8zFYP3uRp+iJYDGRXD8HkOHE91PXLMvBxFtbtzcDGIphKvPW7CbRZGL96z2kgT9wpPtID",
	"YE4mIGg2vp4nHnrTZpxNM5g21Ez7QBAtdBabOC5zww6LtCRqaaSUvQ2Z9AdwSXZTOHu3wMRtrgHoPVon",
	"llzg/gBOeTPZ13+fbtpItd1ftUSDCVXnv+O7mQmQnAYn52cqUwuSeiOqo8FoMErC45IclkaN1fFgNDhW",
	"mSoxvK7EN8TSDLVZpM9zqoxYsZtafaaTCM3CaKqudJv31e4h0oUMm/W0zA4KTXvigNBu3y+vn4zvZ6PR",
	"vtnWxu2abpl6Xt/890z8YTfu0/BvDAAlS2Xq5IR61EZrUe7XXarF22gfhtBIv5/0gvPUN5WvGWBR1ylF",
	"1X8bi739f1kb8v4/oIAP39z4ffCY+5dPRlbXgs8Ob4GPs70tuKwGZB4+tWBfCy67FbJB/xcfQ7/9AP32",
	"E/P7mD9Zr/EN2j8/gPaUg2TRsPnk98WmmUqWgPDVaDRK2aIUaqyGanm9/CsAAP//Linu4BoOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
